config:
  db:
    url: postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    name: ${DB_NAME:postgres}
    schema: ${DB_SCHEMA:public}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  new-database-config:
    prefix: project_
    postfix: _research
  jwks:
    url: ${JWK_URL:http://localhost:3567/recipe/jwt/jwks}
  account-service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8080}

logging:
  level:
    root: info

spring:
  flyway:
    url: jdbc:${config.db.url}
    user: ${config.db.user}
    password: ${config.db.password}

server:
  port: 3030
